### PR TITLE
Popup improvements

### LINKED ISSUE #52: Update map popup
The following changes were requested:

- [ ] Remove hyperlink on name to detail view
- [ ] Add hyperlink via static "details" link to detail view
- [ ] Add budget size text below org name for each item -- should include "Size: {{ qualifier text }}" e.g. "Size: Grassroots" or "Size: Large"
- [ ] Add some sort of delimiter between org rows

### PR DESCRIPTION
**Pull request by CloudNiner**
## Overview

Updates popup:
- Move link to separate "Details" text
- Remove link from org name
- Add budget size to each item
- Visually separate with borders

If you want to tweak this further, feel free to checkout and commit directly to this branch.

## Demo

screen shot 2017-12-08 at 4 44 08 pm

## Testing

Open some popups of various length.

Tested in Chrome/FF/Safari.

Closes #52

### CODE REVIEW

**Comment by CloudNiner** [comment]
@jcahail @nevillevak how does this look?

**Comment by nevillevak** [comment]
Hi Andrew,

That looks great. Now I’m thinking the “Details” link should be called “View & Analyze” since that’s more descriptive and matches the list view. You could break it over two lines if needed since each org now takes two lines.

What do you think?

Best,
Neville
___________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University
Westphal College of Media Arts & Design
215.571.4439, nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>

On Dec 8, 2017, at 4:45 PM, Andrew Fink <notifications@github.com<mailto:notifications@github.com>> wrote:


@jcahail<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcahail&data=02%7C01%7Cnkv22%40drexel.edu%7C1d658c94bb44461a606a08d53e84ff13%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C636483663297425107&sdata=6DHxixEeZlyIHl9CyK6UXdSEBjl%2FHObtssROxvs9a8s%3D&reserved=0> @nevillevak<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnevillevak&data=02%7C01%7Cnkv22%40drexel.edu%7C1d658c94bb44461a606a08d53e84ff13%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C636483663297425107&sdata=9A1XD%2BmA1qtBAhEw0tzAYrMrPOYJOvFbj2Dbw4keLr0%3D&reserved=0> how does this look?

**Comment by CloudNiner** [comment]
"View & Analyze" might look weird over two lines. In addition, there are some cases where org budget size is empty and org name is only one line, so while uncommon, its possible that an org could only fill one line. It's likely best for simplicity to just keep the text "Details"

**Comment by nevillevak** [comment]
Ok. How about "Analyze"?

_____________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University
Westphal College of Media Arts & Design
215.571.4439
nvakharia@drexel.edu

________________________________

**Comment by CloudNiner** [comment]
Updated to "Analyze", I think that will work:

screen shot 2017-12-11 at 8 45 19 am

**Comment by nevillevak** [comment]
Nice. Thanks!

Best,
Neville
_________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, Suite 210
nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>
215.571.4439

**Comment by CloudNiner** [comment]
Merging, this received an offline 👍  from @designmatty

**Pull request merged**
