### PR TITLE
theme, map popups, favicon

### LINKED ISSUE #32: Add Content for "About "Getting Started" and "Contact"
Attached is the text content for the three pages. Note that once it's all up and we have everything in place, I'll likely have some minor edits to it. 
----
Note:
- for the impactview logo, please add the "beta" tag as we've done with MuseumStat
- I don't think we need the three footer text blocks as we did with MuseumStat, but we do need the Drexel Westphal Logo and the Stanford PACS logo (I can re-send if needed).
- As discussed, we'll go with a light-colored design, not the gray/dark used in MuseumStat. 
----
[ImpactView Philadelphia - Web Content and Other Details.docx](https://github.com/ImpactView/impact-view-philly/files/1485720/ImpactView.Philadelphia.-.Web.Content.and.Other.Details.docx)

### LINKED ISSUE #37: De-conflict the org hover interactivity and demographic layer interactivity
There are two cases to address:

screen shot 2017-11-22 at 12 33 50
screen shot 2017-11-22 at 12 33 36

@deisgnmatty I'd be interested in your input and whether you think this is something you can address via styling or whether I need to spend some time looking at how to re-orient with JS.

### LINKED ISSUE #38: Make "click to close" map tool interaction more obvious
Comment by @KlaasH  on #31:
"it wasn't immediately obvious to me that I could close the controls by clicking their title bar. A little "x" or upside-down-caret on the right side of the bar might be a useful prompt."

screen shot 2017-11-22 at 12 36 58

### LINKED ISSUE #42: Style demographic layer hover
image

See also #37

### LINKED ISSUE #43: Add Azavea logo

### PR DESCRIPTION
**Pull request by designmatty**
- Updates the theme from dark to light
- updates favicons
- updated footer logos
- fix map popup issues
- add close icon to map tools

### Preview
**Pop up conflicts**
Moves demographic popup to left of mouse, location popup to right
screen shot 2017-12-04 at 4 35 45 pm

**Light theme**
localhost_9900_ 1

localhost_9900_ 2

localhost_9900_

**Close button on map tools**
screen shot 2017-12-04 at 4 52 54 pm

### Related issues
- Address the rest of and closes #32 
- Fix #42 
- Fix #37 
- Fix #43 
- Fix #38

### CODE REVIEW

**Review by CloudNiner — COMMENTED** [review]
Looks good overall.

A few minor things:

The highlight text in the search dropdown is still white:
screen shot 2017-12-04 at 5 24 04 pm
screen shot 2017-12-04 at 5 24 12 pm

The fill color of leaflet-draw.js while drawing is a pink, which may not look so good with orange. Maybe we should change to something more appropriate?

screen shot 2017-12-04 at 5 25 27 pm

In general the orange is super difficult to read on white. I really don't like it. Willing to be overridden by @jcahail and @nevillevak but it would be nice to get a darker color with better contrast.

**Comment by CloudNiner** [comment]
I should also note that I tested in Chrome/FF/Safari and they all looked consistent.

**Comment by designmatty** [comment]
I agree the orange is a tough to read on white. 

**Changed the pink to orange:**
screen shot 2017-12-05 at 9 51 09 am

**Fixed the color of highlighted text in dropdown and add italics so it's more apparent:**
screen shot 2017-12-05 at 10 08 53 am

**Comment by jcahail** [comment]
I also agree that the orange is difficult to read on white. @nevillevak is there a darker orange or additional color in the palette we might be able to try?

**Comment by nevillevak** [comment]
Hi All – The orange isn’t bad, but I’m fine with a darker orange, to align with the logo color, or if that still isn’t good perhaps a maroon or dark blue? I’ll look to @designmatt’s and your suggestions.

Best,
Neville
_________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, Suite 210
nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>
215.571.4439

**Comment by designmatty** [comment]
I updated the primary color to a darker blue from yellow/orange for readability. 

I also took care of the two tasks assigned to me in #48 
- For “Print the Report” – update footer text and logo. 
  - Footer text updated.
  - There was an issue with printing the logo in the way it was implemented. I replaced the logo with the website url. While this wasn't anticipated, I think there is a lot of value in displaying the exact website location to generate this type of data.
- Demographics hover text - make the text all the same size at the values displayed. Also, make the text a color that is easily readable.
  - Text is now equal in size and uses the blue primary color to help it stand out.

### Demo
localhost_9900_ 3

**Review by CloudNiner — APPROVED** [review]
Looks great.

I noticed that our demographics hover div displays under the map controls but the Carto one for the points layer displays over:

screen shot 2017-12-06 at 4 37 38 pm
screen shot 2017-12-06 at 4 37 33 pm

I'm assuming we'd want to have both hover divs show over the map controls. If you agree and want to tweak, go for it, otherwise I'll fix it when I address the remaining other issues.

**Comment by CloudNiner** [comment]
Oh. I also noticed in my screenshot I just posted that the org location marker is still a museumstat teal. Should we make that either the new highlight blue or logo orange?

**Comment by designmatty** [comment]
I don't have the technical know-how to fix the layering issue. It's a matter of rearranging the dom and css won't be enough.

I'm going to update the map pin and then merge in.

**Comment by designmatty** [comment]
Updated pin.
screen shot 2017-12-07 at 8 55 28 am

**Comment by CloudNiner** [comment]
Got it. I'll see if I can tweak the layering issue. Pin looks great!

**Pull request merged**
